# ## Add your custom plugin specific Environment Variables.

TECH_XL_ENDPOINT=""
TTK_TOKEN_SECRET="BmThdDKu4lPOFiiqwHG1GQVm7iGeVIqALcqwJDM6VySzVdOwZ1UMoylzwhIDgXl6"
TTK_API_BASE_URL="TPL_TTK_API_BASE_URL"
TTK_ORDER_UPDATE_ROUTE="TPL_TTK_ORDER_UPDATE_ROUTE"
TTK_PAYMENT_UPDATE_ROUTE="TPL_TTK_PAYMENT_UPDATE_ROUTE"
ADDON_FILE="add_ons.json"
LINK_RECORD_ORDER_FILE="link_record_ordered_mapping.json"

# Payu Payment Plugins
PAYU_MERCHANT_KEY="TPL_PAYU_MERCHANT_KEY"
PAYU_SALT="TPL_PAYU_SALT"
PAYU_URL="TPL_PAYU_URL"
PAYU_PRODUCT_INFO="TPL_PAYU_PRODUCT_INFO"

TTK_APPOINTMENT_API_ROUTE="TPL_TTK_APPOINTMENT_API_ROUTE"
TTK_DOCUMENT_LIST_API="TPL_TTK_DOCUMENT_LIST_API"
TTK_DOCUMENT_LIST_BY_ID_API="TPL_TTK_DOCUMENT_LIST_BY_ID_API"
TTK_NOTIFICATION_API_ROUTE="TPL_TTK_NOTIFICATION_API_ROUTE"