# generated by datamodel-codegen:
#   filename:  Egyptpdfmodel_schema.json
#   timestamp: 2025-12-12T07:31:04+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Egyptpdfmodel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    passport_passport_details_surname: Optional[str] = Field(
        '', alias='passport.passport_details.surname', description=''
    )
    passport_passport_details_first_name: Optional[str] = Field(
        '', alias='passport.passport_details.first_name', description=''
    )
    Text3: Optional[str] = Field('', description='')
    passport_passport_details_gender: Optional[str] = Field(
        '', alias='passport.passport_details.gender', description=''
    )
    passport_passport_details_place_of_birth: Optional[str] = Field(
        '', alias='passport.passport_details.place_of_birth', description=''
    )
    passport_passport_details_date_of_birth: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_birth', description=''
    )
    passport_passport_details_nationality: Optional[str] = Field(
        '', alias='passport.passport_details.nationality', description=''
    )
    passport_passport_details_nationality_of_origin: Optional[str] = Field(
        '', alias='passport.passport_details.nationality_of_origin', description=''
    )
    work_address_work_details_occupation: Optional[str] = Field(
        '', alias='work_address.work_details.occupation', description=''
    )
    Text10: Optional[str] = Field('', description='')
    passport_passport_details_date_of_expiry: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_expiry', description=''
    )
    passport_passport_details_date_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_issue', description=''
    )
    passport_passport_details_place_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.place_of_issue', description=''
    )
    passport_passport_details_passport_number: Optional[str] = Field(
        '', alias='passport.passport_details.passport_number', description=''
    )
    residential_address_residential_address_card_v1_address_line_1_present_address: Optional[
        str
    ] = Field(
        '',
        alias='residential_address.residential_address_card_v1.address_line_1_present_address',
        description='',
    )
    residential_address_residential_address_card_v1_address_line_1_permanent_address: Optional[
        str
    ] = Field(
        '',
        alias='residential_address.residential_address_card_v1.address_line_1_permanent_address',
        description='',
    )
    visa_request_information_visa_request_phone_number_permanent_address: Optional[
        str
    ] = Field(
        '',
        alias='visa_request_information.visa_request.phone_number_permanent_address',
        description='',
    )
    visa_request_information_visa_request_phone_number_present_address: Optional[
        str
    ] = Field(
        '',
        alias='visa_request_information.visa_request.phone_number_present_address',
        description='',
    )
    visa_request_information_visa_request_purpose_of_stay: Optional[str] = Field(
        '',
        alias='visa_request_information.visa_request.purpose_of_stay',
        description='',
    )
    ticketing_flight_tickets_arrival_date: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.arrival_date', description=''
    )
    visa_request_information_visa_request_length_of_stay: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.length_of_stay', description=''
    )
    visa_request_information_visa_request_no_of_entries: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.no_of_entries', description=''
    )
    ticketing_flight_tickets_port_of_entry: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.port_of_entry', description=''
    )
    Text24: Optional[str] = Field('', description='')
    accomodation_invitation_details_inviter_name1: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_name1', description=''
    )
    accomodation_invitation_details_inviter_name2: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_name2', description=''
    )
    accomodation_invitation_details_inviter_name3: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_name3', description=''
    )
    accomodation_invitation_details_inviter_name4: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_name4', description=''
    )
    accomodation_invitation_details_inviter_address1: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_address1', description=''
    )
    accomodation_invitation_details_inviter_address2: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_address2', description=''
    )
    accomodation_invitation_details_inviter_address3: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_address3', description=''
    )
    accomodation_invitation_details_inviter_address4: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_address4', description=''
    )
    Text33: Optional[str] = Field('', description='')
    Text34: Optional[str] = Field('', description='')
    passport_travel_companion_details_companion_name1: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_name1', description=''
    )
    passport_travel_companion_details_relationship_with_applicant1: Optional[
        str
    ] = Field(
        '',
        alias='passport.travel_companion_details.relationship_with_applicant1',
        description='',
    )
    passport_travel_companion_details_companion_dob1: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_dob1', description=''
    )
    Text50: Optional[str] = Field('', description='')
    Text55: Optional[str] = Field('', description='')
    previous_visas_visit_details_previous_visit_date1: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_date1', description=''
    )
    previous_visas_visit_details_previous_visit_purpose1: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_purpose1', description=''
    )
    previous_visas_visit_details_previous_visit_address1: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_address1', description=''
    )
    Text43: Optional[str] = Field('', description='')
    Text44: Optional[str] = Field('', description='')
    Text45: Optional[str] = Field('', description='')
    Text46: Optional[str] = Field('', description='')
    Text47: Optional[str] = Field('', description='')
    Text48: Optional[str] = Field('', description='')
    passport_travel_companion_details_companion_name2: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_name2', description=''
    )
    passport_travel_companion_details_companion_name3: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_name3', description=''
    )
    passport_travel_companion_details_companion_name4: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_name4', description=''
    )
    passport_travel_companion_details_companion_name5: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_name5', description=''
    )
    passport_travel_companion_details_relationship_with_applicant2: Optional[
        str
    ] = Field(
        '',
        alias='passport.travel_companion_details.relationship_with_applicant2',
        description='',
    )
    passport_travel_companion_details_relationship_with_applicant3: Optional[
        str
    ] = Field(
        '',
        alias='passport.travel_companion_details.relationship_with_applicant3',
        description='',
    )
    passport_travel_companion_details_relationship_with_applicant4: Optional[
        str
    ] = Field(
        '',
        alias='passport.travel_companion_details.relationship_with_applicant4',
        description='',
    )
    passport_travel_companion_details_relationship_with_applicant5: Optional[
        str
    ] = Field(
        '',
        alias='passport.travel_companion_details.relationship_with_applicant5',
        description='',
    )
    passport_travel_companion_details_companion_dob2: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_dob2', description=''
    )
    passport_travel_companion_details_companion_dob3: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_dob3', description=''
    )
    passport_travel_companion_details_companion_dob4: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_dob4', description=''
    )
    passport_travel_companion_details_companion_dob5: Optional[str] = Field(
        '', alias='passport.travel_companion_details.companion_dob5', description=''
    )
    previous_visas_visit_details_previous_visit_address2: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_address2', description=''
    )
    previous_visas_visit_details_previous_visit_address3: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_address3', description=''
    )
    previous_visas_visit_details_previous_visit_address4: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_address4', description=''
    )
    previous_visas_visit_details_previous_visit_address5: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_address5', description=''
    )
    previous_visas_visit_details_previous_visit_date2: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_date2', description=''
    )
    previous_visas_visit_details_previous_visit_date3: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_date3', description=''
    )
    previous_visas_visit_details_previous_visit_date4: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_date4', description=''
    )
    previous_visas_visit_details_previous_visit_date5: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_date5', description=''
    )
    previous_visas_visit_details_previous_visit_purpose2: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_purpose2', description=''
    )
    previous_visas_visit_details_previous_visit_purpose3: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_purpose3', description=''
    )
    previous_visas_visit_details_previous_visit_purpose4: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_purpose4', description=''
    )
    previous_visas_visit_details_previous_visit_purpose5: Optional[str] = Field(
        '', alias='previous_visas.visit_details.previous_visit_purpose5', description=''
    )
    Text51: Optional[str] = Field('', description='')
    Text38: Optional[str] = Field('', description='')
    Text54: Optional[str] = Field('', description='')
    Text56: Optional[str] = Field('', description='')
    Text57: Optional[str] = Field('', description='')
    Text58: Optional[str] = Field('', description='')
    Text59: Optional[str] = Field('', description='')
    passport_travel_companion_details_companion_place_of_birth1: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_place_of_birth1',
        description='',
    )
    passport_travel_companion_details_companion_place_of_birth2: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_place_of_birth2',
        description='',
    )
    passport_travel_companion_details_companion_place_of_birth3: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_place_of_birth3',
        description='',
    )
    passport_travel_companion_details_companion_place_of_birth4: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_place_of_birth4',
        description='',
    )
    passport_travel_companion_details_companion_place_of_birth5: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_place_of_birth5',
        description='',
    )
    Text66: Optional[str] = Field('', description='')
    Text67: Optional[str] = Field('', description='')
    Text68: Optional[str] = Field('', description='')
    Text69: Optional[str] = Field('', description='')
    Text70: Optional[str] = Field('', description='')
