# generated by datamodel-codegen:
#   filename:  Japanpdfmodel_schema.json
#   timestamp: 2025-12-12T06:49:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Japanpdfmodel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    passport_passport_details_surname: Optional[str] = Field(
        '', alias='passport.passport_details.surname', description=''
    )
    passport_passport_details_first_name: Optional[str] = Field(
        '', alias='passport.passport_details.first_name', description=''
    )
    passport_passport_details_place_of_birth: Optional[str] = Field(
        '', alias='passport.passport_details.place_of_birth', description=''
    )
    passport_passport_details_nationality: Optional[str] = Field(
        '', alias='passport.passport_details.nationality', description=''
    )
    passport_other_details_other_nationality: Optional[str] = Field(
        '', alias='passport.other_details.other_nationality', description=''
    )
    additional_details_national_id_aadhaar_number: Optional[str] = Field(
        '', alias='additional_details.national_id.aadhaar_number', description=''
    )
    passport_passport_details_passport_number: Optional[str] = Field(
        '', alias='passport.passport_details.passport_number', description=''
    )
    passport_passport_details_place_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.place_of_issue', description=''
    )
    passport_passport_details_date_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_issue', description=''
    )
    passport_passport_details_issued_by: Optional[str] = Field(
        '', alias='passport.passport_details.issued_by', description=''
    )
    work_address_work_details_certificate_of_eligibility: Optional[str] = Field(
        '', alias='work_address.work_details.certificate_of_eligibility', description=''
    )
    visa_request_information_visa_request_purpose_of_stay: Optional[str] = Field(
        '',
        alias='visa_request_information.visa_request.purpose_of_stay',
        description='',
    )
    visa_request_information_visa_request_length_of_stay: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.length_of_stay', description=''
    )
    ticketing_flight_tickets_arrival_date: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.arrival_date', description=''
    )
    ticketing_flight_tickets_airline: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.airline', description=''
    )
    accomodation_booked_appointment_accommodation_name: Optional[str] = Field(
        '', alias='accomodation.booked_appointment.accommodation_name', description=''
    )
    accomodation_booked_appointment_mobile_number: Optional[str] = Field(
        '', alias='accomodation.booked_appointment.mobile_number', description=''
    )
    accomodation_booked_appointment_accommodation_address: Optional[str] = Field(
        '',
        alias='accomodation.booked_appointment.accommodation_address',
        description='',
    )
    Dates_and_duration_of_previous_stays_in_Japan: Optional[str] = Field(
        '', alias='Dates and duration of previous stays in Japan', description=''
    )
    passport_passport_details_address_line_1: Optional[str] = Field(
        '', alias='passport.passport_details.address_line_1', description=''
    )
    Te_I: Optional[str] = Field('', alias='Te I', description='')
    visa_request_information_visa_request_phone_number: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.phone_number', description=''
    )
    visa_request_information_visa_request_email_id: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.email_id', description=''
    )
    work_address_work_details_occupation: Optional[str] = Field(
        '', alias='work_address.work_details.occupation', description=''
    )
    work_address_work_details_employer_name: Optional[str] = Field(
        '', alias='work_address.work_details.employer_name', description=''
    )
    work_address_work_details_work_phone: Optional[str] = Field(
        '', alias='work_address.work_details.work_phone', description=''
    )
    work_address_work_details_work_address: Optional[str] = Field(
        '', alias='work_address.work_details.work_address', description=''
    )
    passport_passport_details_surname_at_birth: Optional[str] = Field(
        '', alias='passport.passport_details.surname_at_birth', description=''
    )
    passport_passport_details_date_of_birth: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_birth', description=''
    )
    passport_passport_details_gender_male: Optional[bool] = Field(
        False, alias='passport.passport_details.gender_male', description=''
    )
    passport_passport_details_gender_female: Optional[bool] = Field(
        False, alias='passport.passport_details.gender_female', description=''
    )
    passport_other_details_other_civil_status_single: Optional[bool] = Field(
        False, alias='passport.other_details.other_civil_status_single', description=''
    )
    passport_other_details_other_civil_status_married: Optional[bool] = Field(
        False, alias='passport.other_details.other_civil_status_married', description=''
    )
    passport_other_details_other_civil_status_widowed: Optional[bool] = Field(
        False, alias='passport.other_details.other_civil_status_widowed', description=''
    )
    passport_other_details_other_civil_status_divorced: Optional[bool] = Field(
        False,
        alias='passport.other_details.other_civil_status_divorced',
        description='',
    )
    passport_passport_details_type_of_passport_diplomatic: Optional[bool] = Field(
        False,
        alias='passport.passport_details.type_of_passport_diplomatic',
        description='',
    )
    passport_passport_details_type_of_passport_official: Optional[bool] = Field(
        False,
        alias='passport.passport_details.type_of_passport_official',
        description='',
    )
    passport_passport_details_type_of_passport_ordinary: Optional[bool] = Field(
        False,
        alias='passport.passport_details.type_of_passport_ordinary',
        description='',
    )
    passport_passport_details_type_of_passport_other: Optional[bool] = Field(
        False, alias='passport.passport_details.type_of_passport_other', description=''
    )
    passport_passport_details_date_of_expiry: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_expiry', description=''
    )
    ticketing_flight_tickets_port_of_entry: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.port_of_entry', description=''
    )
    passport_other_details_partner_parent_occupation: Optional[str] = Field(
        '', alias='passport.other_details.partner_parent_occupation', description=''
    )
    accomodation_guarantor_details_guarantor_inviter_name: Optional[str] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_name',
        description='',
    )
    Tel_3: Optional[str] = Field('', description='')
    accomodation_guarantor_details_guarantor_inviter_address: Optional[str] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_address',
        description='',
    )
    accomodation_guarantor_details_guarantor_inviter_dob: Optional[str] = Field(
        '', alias='accomodation.guarantor_details.guarantor_inviter_dob', description=''
    )
    accomodation_guarantor_details_guarantor_inviter_relationship: Optional[
        str
    ] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_relationship',
        description='',
    )
    accomodation_guarantor_details_guarantor_inviter_occupation: Optional[str] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_occupation',
        description='',
    )
    accomodation_guarantor_details_guarantor_inviter_nationality: Optional[str] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_nationality',
        description='',
    )
    accomodation_invitation_details_inviter_name: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_name', description=''
    )
    Tel_4: Optional[str] = Field('', description='')
    accomodation_invitation_details_inviter_address: Optional[str] = Field(
        '', alias='accomodation.invitation_details.inviter_address', description=''
    )
    accomodation_invitation_details_relationship: Optional[str] = Field(
        '', alias='accomodation.invitation_details.relationship', description=''
    )
    accomodation_invitation_details_guarantor_inviter_occupation: Optional[str] = Field(
        '',
        alias='accomodation.invitation_details.guarantor_inviter_occupation',
        description='',
    )
    accomodation_invitation_details_guarantor_inviter_nationality: Optional[
        str
    ] = Field(
        '',
        alias='accomodation.invitation_details.guarantor_inviter_nationality',
        description='',
    )
    Note_Rem_arksSpec_i_a_I_circumstances_if_any: Optional[str] = Field(
        '', alias='Note Rem arksSpec i a I circumstances if any', description=''
    )
    declaration_applicant_antecedent_crime_conviction_yes: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.crime_conviction_yes',
        description='',
    )
    declaration_applicant_antecedent_crime_conviction_no: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.crime_conviction_no',
        description='',
    )
    declaration_applicant_antecedent_imprisonment_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.imprisonment_yes', description=''
    )
    declaration_applicant_antecedent_imprisonment_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.imprisonment_no', description=''
    )
    declaration_applicant_antecedent_deported_japan_yes: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.deported_japan_yes',
        description='',
    )
    declaration_applicant_antecedent_deported_japan_no: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.deported_japan_no',
        description='',
    )
    declaration_applicant_antecedent_drug_offence_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.drug_offence_yes', description=''
    )
    declaration_applicant_antecedent_drug_offence_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.drug_offence_no', description=''
    )
    declaration_applicant_antecedent_prostitution_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.prostitution_yes', description=''
    )
    declaration_applicant_antecedent_trafficking_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.trafficking_yes', description=''
    )
    declaration_applicant_antecedent_trafficking_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.trafficking_no', description=''
    )
    declaration_applicant_antecedent_prostitution_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.prostitution_no', description=''
    )
    declaration_applicant_antecedent_furnish_details: Optional[str] = Field(
        '', alias='declaration.applicant_antecedent.furnish_details', description=''
    )
    accomodation_guarantor_details_guarantor_inviter_gender_male: Optional[
        bool
    ] = Field(
        False,
        alias='accomodation.guarantor_details.guarantor_inviter_gender_male',
        description='',
    )
    accomodation_guarantor_details_guarantor_inviter_gender_female: Optional[
        bool
    ] = Field(
        False,
        alias='accomodation.guarantor_details.guarantor_inviter_gender_female',
        description='',
    )
    accomodation_invitation_details_guarantor_inviter_gender_male: Optional[
        bool
    ] = Field(
        False,
        alias='accomodation.invitation_details.guarantor_inviter_gender_male',
        description='',
    )
    accomodation_invitation_details_guarantor_inviter_gender_female: Optional[
        bool
    ] = Field(
        False,
        alias='accomodation.invitation_details.guarantor_inviter_gender_female',
        description='',
    )
    accomodation_invitation_details_guarantor_inviter_dob: Optional[str] = Field(
        '',
        alias='accomodation.invitation_details.guarantor_inviter_dob',
        description='',
    )
    accomodation_invitation_details_guarantor_inviter_immigration_stat: Optional[
        str
    ] = Field(
        '',
        alias='accomodation.invitation_details.guarantor_inviter_immigration_stat',
        description='',
    )
    accomodation_guarantor_details_guarantor_inviter_immigration_stat: Optional[
        str
    ] = Field(
        '',
        alias='accomodation.guarantor_details.guarantor_inviter_immigration_stat',
        description='',
    )
    Text6: Optional[str] = Field('', description='')
