# generated by datamodel-codegen:
#   filename:  Mexicopdfmodel_schema.json
#   timestamp: 2025-12-07T18:04:20+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Mexicopdfmodel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    passport_passport_details_first_name: Optional[str] = Field(
        '', alias='passport.passport_details.first_name', description=''
    )
    Text3: Optional[str] = Field('', description='')
    passport_passport_details_date_of_birth_dd: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_birth_dd', description=''
    )
    passport_passport_details_date_of_birth_mm: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_birth_mm', description=''
    )
    passport_passport_details_date_of_birth_yyyy: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_birth_yyyy', description=''
    )
    passport_passport_details_age: Optional[str] = Field(
        '', alias='passport.passport_details.age', description=''
    )
    passport_passport_details_surname: Optional[str] = Field(
        '', alias='passport.passport_details.surname', description=''
    )
    passport_passport_details_country_of_birth: Optional[str] = Field(
        '', alias='passport.passport_details.country_of_birth', description=''
    )
    passport_passport_details_nationality: Optional[str] = Field(
        '', alias='passport.passport_details.nationality', description=''
    )
    passport_travel_companion_details_companion_passport_num: Optional[str] = Field(
        '',
        alias='passport.travel_companion_details.companion_passport_num',
        description='',
    )
    passport_passport_details_country_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.country_of_issue', description=''
    )
    passport_passport_details_date_of_issue: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_issue', description=''
    )
    passport_passport_details_date_of_expiry_dd: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_expiry_dd', description=''
    )
    passport_passport_details_date_of_expiry_mm: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_expiry_mm', description=''
    )
    passport_passport_details_date_of_expiry_yyyy: Optional[str] = Field(
        '', alias='passport.passport_details.date_of_expiry_yyyy', description=''
    )
    residential_address_residential_address_card_v1_type_of_proof: Optional[
        str
    ] = Field(
        '',
        alias='residential_address.residential_address_card_v1.type_of_proof',
        description='',
    )
    visa_request_information_visa_request_phone_number: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.phone_number', description=''
    )
    visa_request_information_visa_request_email_id: Optional[str] = Field(
        '', alias='visa_request_information.visa_request.email_id', description=''
    )
    work_address_work_details_occupation: Optional[str] = Field(
        '', alias='work_address.work_details.occupation', description=''
    )
    work_address_work_details_employer_name: Optional[str] = Field(
        '', alias='work_address.work_details.employer_name', description=''
    )
    passport_passport_details_country: Optional[str] = Field(
        '', alias='passport.passport_details.country', description=''
    )
    declaration_applicant_antecedent_furnish_details_1: Optional[str] = Field(
        '', alias='declaration.applicant_antecedent.furnish_details_1', description=''
    )
    ticketing_flight_tickets_arrival_date_dd: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.arrival_date_dd', description=''
    )
    ticketing_flight_tickets_arrival_date_mm: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.arrival_date_mm', description=''
    )
    ticketing_flight_tickets_arrival_date_yyyy: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.arrival_date_yyyy', description=''
    )
    ticketing_flight_tickets_port_of_entry: Optional[str] = Field(
        '', alias='ticketing.flight_tickets.port_of_entry', description=''
    )
    declaration_applicant_antecedent_furnish_details: Optional[str] = Field(
        '', alias='declaration.applicant_antecedent.furnish_details', description=''
    )
    visa_request_information_visa_request_purpose_of_stay: Optional[str] = Field(
        '',
        alias='visa_request_information.visa_request.purpose_of_stay',
        description='',
    )
    passport_passport_details_gender_male: Optional[bool] = Field(
        False, alias='passport.passport_details.gender_male', description=''
    )
    passport_passport_details_gender_no_specific: Optional[bool] = Field(
        False, alias='passport.passport_details.gender_no_specific', description=''
    )
    passport_passport_details_gender_female: Optional[bool] = Field(
        False, alias='passport.passport_details.gender_female', description=''
    )
    passport_other_details_other_civil_status_single: Optional[bool] = Field(
        False, alias='passport.other_details.other_civil_status_single', description=''
    )
    passport_other_details_other_civil_status_married: Optional[bool] = Field(
        False, alias='passport.other_details.other_civil_status_married', description=''
    )
    passport_other_details_other_civil_status_common_law: Optional[bool] = Field(
        False,
        alias='passport.other_details.other_civil_status_common_law',
        description='',
    )
    passport_other_details_legal_migratory_status_yes: Optional[bool] = Field(
        False, alias='passport.other_details.legal_migratory_status_yes', description=''
    )
    passport_other_details_legal_migratory_status_no: Optional[bool] = Field(
        False, alias='passport.other_details.legal_migratory_status_no', description=''
    )
    declaration_applicant_antecedent_prohibited_entry_yes: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.prohibited_entry_yes',
        description='',
    )
    declaration_applicant_antecedent_prohibited_entry_no: Optional[bool] = Field(
        False,
        alias='declaration.applicant_antecedent.prohibited_entry_no',
        description='',
    )
    declaration_applicant_antecedent_denied_entry_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.denied_entry_yes', description=''
    )
    declaration_applicant_antecedent_denied_entry_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.denied_entry_no', description=''
    )
    declaration_applicant_antecedent_convincted_yes: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.convincted_yes', description=''
    )
    declaration_applicant_antecedent_convincted_no: Optional[bool] = Field(
        False, alias='declaration.applicant_antecedent.convincted_no', description=''
    )
    visa_request_information_visa_request_length_of_stay_below180: Optional[
        bool
    ] = Field(
        False,
        alias='visa_request_information.visa_request.length_of_stay_below180',
        description='',
    )
    visa_request_information_visa_request_length_of_stay_above180: Optional[
        bool
    ] = Field(
        False,
        alias='visa_request_information.visa_request.length_of_stay_above180',
        description='',
    )
    visa_request_information_visa_request_length_of_stay_definitive: Optional[
        bool
    ] = Field(
        False,
        alias='visa_request_information.visa_request.length_of_stay_definitive',
        description='',
    )
    visa_request_information_visa_request_visa_type_tourist: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_tourist',
        description='',
    )
    visa_request_information_visa_request_visa_type_long_term_visitor: Optional[
        bool
    ] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_long_term_visitor',
        description='',
    )
    visa_request_information_visa_request_visa_type_work: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_work',
        description='',
    )
    visa_request_information_visa_request_visa_type_conducting_adoption: Optional[
        bool
    ] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_conducting_adoption',
        description='',
    )
    visa_request_information_visa_request_visa_type_student: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_student',
        description='',
    )
    visa_request_information_visa_request_visa_type_temp_res: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_temp_res',
        description='',
    )
    visa_request_information_visa_request_visa_type_permanent: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_permanent',
        description='',
    )
    visa_request_information_visa_request_visa_type_diplomatic: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_diplomatic',
        description='',
    )
    visa_request_information_visa_request_visa_type_official: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_official',
        description='',
    )
    visa_request_information_visa_request_visa_type_service: Optional[bool] = Field(
        False,
        alias='visa_request_information.visa_request.visa_type_service',
        description='',
    )
    Check_passport_passport_details_type_of_passport_regular: Optional[bool] = Field(
        False,
        alias='Check passport.passport_details.type_of_passport_regular',
        description='',
    )
    Check_passport_passport_details_type_of_passport_regular_passer: Optional[
        bool
    ] = Field(
        False,
        alias='Check passport.passport_details.type_of_passport_regular_passer',
        description='',
    )
    Check_passport_passport_details_type_of_passport_regular_special: Optional[
        bool
    ] = Field(
        False,
        alias='Check passport.passport_details.type_of_passport_regular_special',
        description='',
    )
    Text1: Optional[str] = Field('', description='')
    Text2: Optional[str] = Field('', description='')
    Text4: Optional[str] = Field('', description='')
    Text5: Optional[str] = Field('', description='')
