from pydantic import BaseModel
from typing import Optional


class PDFModel(BaseModel):
    visa_surname_family_name: str = ""
    visa_surname_at_birth: str = ""
    visa_first_name: str = ""
    visa_dob: str = ""
    visa_cob: str = ""
    visa_sex_male: Optional[bool] = False
    visa_sex_female: Optional[bool] = False
    visa_sex_oth: Optional[bool] = False
    visa_civil_sts_single: Optional[bool] = False
    visa_civil_sts_married: Optional[bool] = False
    visa_civil_sts_seperated: Optional[bool] = False
    visa_civil_sts_divorced: Optional[bool] = False
    visa_civil_sts_widow: Optional[bool] = False
    visa_civil_sts_reg_partner: Optional[bool] = False
    visa_civil_sts_oth: Optional[bool] = False
    visa_pob: str = ""
    visa_curr_natl: str = ""
    visa_oth_natl: str = ""
    visa_civil_sts_oth_txt: str = ""
    visa_natl_at_birth: str = ""
    visa_parental_auth: str = ""
    visa_nat_id_num: str = ""
    visa_typ_trav_doc_ord: Optional[bool] = False
    visa_typ_trav_doc_service: Optional[bool] = False
    visa_typ_trav_doc_special: Optional[bool] = False
    visa_num_trav_doc: str = ""
    visa_fam_mem_eu_surname: str = ""
    visa_fam_mem_eu_dob: str = ""
    visa_doi: str = ""
    visa_val_til: str = ""
    visa_issued_by_ctry: str = ""
    visa_fam_mem_eu_1st_nm: str = ""
    visa_fam_mem_eu_natl: str = ""
    visa_fam_mem_eu_num_trav_doc: str = ""
    visa_fam_rs_eu_spouse: Optional[bool] = False
    visa_fam_rs_eu_child: Optional[bool] = False
    visa_fam_rs_eu_gc: Optional[bool] = False
    visa_fam_rs_eu_dependent: Optional[bool] = False
    visa_fam_rs_eu_registered: Optional[bool] = False
    visa_fam_rs_eu_oth: Optional[bool] = False
    visa_oth_trav_doc_txt: str = ""
    visa_fam_rs_eu_oth_txt: str = ""
    visa_typ_trav_doc_diplomatic: Optional[bool] = False
    visa_typ_trav_doc_official: Optional[bool] = False
    visa_typ_trav_doc_oth: Optional[bool] = False
    visa_app_addr: str = ""
    visa_app_tel_num: str = ""
    visa_oth_natl_no: Optional[bool] = False
    visa_oth_natl_yes: Optional[bool] = False
    visa_curr_occ: str = ""
    visa_emp_stu_add_tel: str = ""
    visa_jrn_purpose_visit_fnf: Optional[bool] = False
    visa_jrn_purpose_tour: Optional[bool] = False
    visa_jrn_purpose_business: Optional[bool] = False
    visa_jrn_purpose_culture: Optional[bool] = False
    visa_jrn_purpose_official: Optional[bool] = False
    visa_jrn_purpose_study: Optional[bool] = False
    visa_jrn_purpose_med: Optional[bool] = False
    visa_jrn_purpose_sports: Optional[bool] = False
    visa_jrn_purpose_transit: Optional[bool] = False
    visa_jrn_purpose_oth: Optional[bool] = False
    visa_addl_stay_info: str = ""
    visa_mem_main_dst: str = ""
    visa_mem_1st_entry: str = ""
    visa_entry_num_req_single: Optional[bool] = False
    visa_entry_num_req_two: Optional[bool] = False
    visa_entry_num_req_multi: Optional[bool] = False
    visa_oth_natl_yes_res_num: str = ""
    visa_oth_natl_yes_val_til: str = ""
    visa_jrn_purpose_oth_txt: str = ""
    visa_invite_temp_accom: str = ""
    visa_invite_temp_accom_comm_details: str = ""
    visa_invite_org: str = ""
    visa_invite_org_comm_details: str = ""
    visa_trav_cost_self: Optional[bool] = False
    visa_trav_cost_self_cash: Optional[bool] = False
    visa_trav_cost_self_tc: Optional[bool] = False
    visa_trav_cost_self_cc: Optional[bool] = False
    visa_trav_cost_self_ppa: Optional[bool] = False
    visa_trav_cost_self_ppt: Optional[bool] = False
    visa_trav_cost_self_oth: Optional[bool] = False
    visa_invite_temp_accom_tel_num: str = ""
    visa_invite_temp_accom_tel_mun: str = ""
    visa_1st_arrival_date: str = ""
    visa_dptr_date: str = ""
    visa_fingerprint_yes_date: str = ""
    visa_fingerprint_yes_sticker_num: str = ""
    visa_permit_final_ctry_dest_issued_by: str = ""
    visa_permit_final_ctry_dest_valid_from: str = ""
    visa_permit_final_ctry_dest_til: str = ""
    visa_trav_cost_self_oth_txt: str = ""
    visa_fingerprint_no: Optional[bool] = False
    visa_fingerprint_yes: Optional[bool] = False
    visa_trav_cost_spons: Optional[bool] = False
    visa_trav_cost_31_32: Optional[bool] = False
    visa_trav_cost_oth: Optional[bool] = False
    visa_trav_cost_oth_txt: str = ""
    visa_means_support_oth_cash: Optional[bool] = False
    visa_means_support_oth_ap: Optional[bool] = False
    visa_means_support_oth_expn_covered: Optional[bool] = False
    visa_means_support_oth_ppt: Optional[bool] = False
    visa_means_support_oth: Optional[bool] = False
    visa_applicant_diff_surnm_nm: str = ""
    visa_applicant_diff_addr: str = ""
    visa_applicant_diff_tel_num: str = ""
    visa_trav_cost_sponsor_txt: str = ""
    visa_means_support_oth_txt: str = ""


# class FieldToggle(Enum):
#     YES = "Yes"
#     NO = "No"


# class EditableForm(BaseModel):
#     visa_surname_family_name: str = ""
#     visa_surname_at_birth: str = ""
#     visa_first_name: str = ""
#     visa_dob: str = ""
#     visa_cob: str = ""
#     visa_sex_male: FieldToggle | str = ""
#     visa_sex_female: FieldToggle | str = ""
#     visa_sex_divers: FieldToggle | str = ""
#     visa_civil_sts_single: FieldToggle | str = ""
#     visa_civil_sts_married: FieldToggle | str = ""
#     visa_civil_sts_seperated: FieldToggle | str = ""
#     visa_civil_sts_divorced: FieldToggle | str = ""
#     visa_civil_widow: FieldToggle | str = ""
#     visa_civil_sts_reg_partner: FieldToggle | str = ""
#     visa_civil_sts_oth: FieldToggle | str = ""
#     visa_pob: str = ""
#     visa_curr_natl: str = ""
#     visa_natl_at_birth: str = ""
#     visa_civil_sts_oth_txt: str = ""
#     visa_parental_auth: str = ""
#     visa_nat_id_num: str = ""
#     visa_typ_trav_doc_ord: FieldToggle | str = ""
#     visa_typ_trav_doc_service: FieldToggle | str = ""
#     visa_typ_trav_doc_special: FieldToggle | str = ""
#     visa_num_trav_doc: str = ""
#     visa_fam_mem_eu_surname: str = ""
#     visa_fam_mem_eu_dob: str = ""
#     visa_doi: str = ""
#     visa_val_til: str = ""
#     visa_issued_by_ctry: str = ""
#     visa_fam_mem_eu_1st_nm: str = ""
#     visa_fam_mem_eu_natl: str = ""
#     visa_fam_mem_eu_num_trav_doc: str = ""
#     visa_fam_rs_eu_spouse: FieldToggle | str = ""
#     visa_fam_rs_eu_child: FieldToggle | str = ""
#     visa_fam_rs_eu_gc: FieldToggle | str = ""
#     visa_fam_rs_eu_dependent: FieldToggle | str = ""
#     visa_fam_rs_eu_registered: FieldToggle | str = ""
#     visa_fam_rs_eu_oth: FieldToggle | str = ""
#     visa_oth_trav_doc_txt: str = ""
#     visa_fam_rs_eu_oth_txt: str = ""
#     visa_typ_trav_doc_diplomatic: FieldToggle | str = ""
#     visa_typ_trav_doc_official: FieldToggle | str = ""
#     visa_typ_trav_doc_oth: FieldToggle | str = ""
#     visa_app_addr: str = ""
#     visa_app_tel_num: str = ""
#     visa_oth_natl_no: FieldToggle | str = ""
#     visa_oth_natl_yes: FieldToggle | str = ""
#     visa_curr_occ: str = ""
#     visa_emp_stu_add_tel_: str = ""
#     visa_jrn_purpose_visit_fnf: FieldToggle | str = ""
#     visa_jrn_purpose_tour: FieldToggle | str = ""
#     visa_jrn_purpose_business: FieldToggle | str = ""
#     visa_jrn_purpose_culture: FieldToggle | str = ""
#     visa_jrn_purpose_official: FieldToggle | str = ""
#     visa_jrn_purpose_study: FieldToggle | str = ""
#     visa_jrn_purpose_med: FieldToggle | str = ""
#     visa_jrn_purpose_sports: FieldToggle | str = ""
#     visa_jrn_purpose_transit: FieldToggle | str = ""
#     visa_jrn_purpose_oth: FieldToggle | str = ""
#     visa_addl_stay_info: str = ""
#     visa_mem_main_dst: str = ""
#     visa_mem_1st_entry: str = ""
#     visa_entry_num_req_single: FieldToggle | str = ""
#     visa_entry_num_req_two: FieldToggle | str = ""
#     visa_entry_num_req_multi: FieldToggle | str = ""
#     visa_oth_natl_yes_res_num: str = ""
#     visa_oth_natl_yes_val_til: str = ""
#     visa_jrn_purpose_oth_txt: str = ""
#     visa_invite_temp_accom: str = ""
#     visa_invite_temp_accom_comm_details: str = ""
#     visa_invite_org: str = ""
#     visa_invite_org_comm_details: str = ""
#     visa_trav_cost_self: FieldToggle | str = ""
#     visa_trav_cost_self_cash: FieldToggle | str = ""
#     visa_trav_cost_self_tc: FieldToggle | str = ""
#     visa_trav_cost_self_cc: FieldToggle | str = ""
#     visa_trav_cost_self_ppa: FieldToggle | str = ""
#     visa_trav_cost_self_ppt: FieldToggle | str = ""
#     visa_trav_cost_self_oth: FieldToggle | str = ""
#     visa_invite_temp_accom_tel_num: str = ""
#     visa_invite_temp_accom_tel_mun: str = ""
#     visa_1st_arrival_date_: str = ""
#     visa_dptr_date: str = ""
#     visa_fingerprint_yes_date: str = ""
#     visa_fingerprint_yes_sticker_num: str = ""
#     visa_permit_final_ctry_dest_issued_by: str = ""
#     visa_permit_final_ctry_dest_valid_from: str = ""
#     visa_permit_final_ctry_dest_til: str = ""
#     visa_trav_cost_self_oth_txt: str = ""
#     visa_fingerprint_no: FieldToggle | str = ""
#     visa_fingerprint_yes: FieldToggle | str = ""
#     visa_trav_cost_spons: FieldToggle | str = ""
#     visa_trav_cost_31_32: FieldToggle | str = ""
#     visa_trav_cost: FieldToggle | str = ""
#     visa_means_support_oth_cash: FieldToggle | str = ""
#     visa_means_support_oth_ap: FieldToggle | str = ""
#     visa_means_support_oth_expn_covered: FieldToggle | str = ""
#     visa_means_support_oth_ppt: FieldToggle | str = ""
#     visa_means_supportoth_oth: FieldToggle | str = ""
#     visa_applicant_diff_surnm_nm: str = ""
#     visa_applicant_diff_addr: str = ""
#     visa_applicant_diff_tel_num: str = ""
#     visa_trav_cost_sponsor_txt: str = ""
#     visa_trav_cost_oth_txt: str = ""
#     visa_means_support_oth_txt: str = ""
